name: food_log
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.5 <4.0.0"

dependencies:
  background_fetch: ^1.2.4
  camera: ^0.10.5+9
  fl_chart: ^0.66.2
  flutter:
    sdk: flutter
  flutter_local_notifications: ^16.3.3
  flutter_map: ^6.1.0
  flutter_secure_storage: ^9.0.0
  go_router: ^13.1.0
  http: ^1.2.0
  latlong2: ^0.9.0
  location: ^5.0.3
  path: ^1.9.0
  path_provider: ^2.1.2
  provider: ^6.1.1
  uuid: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/
